USE [SGX_TEST]
GO

/****** Object:  Table [dbo].[tbl_UOMMaster]    Script Date: 6/19/2024 4:31:10 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[tbl_UOMMaster](
	[UOM_ID] [int] NOT NULL,
	[UOM] [varchar](30) NULL,
	[UOM_CODE] [varchar](10) NULL,
 CONSTRAINT [PK_tbl_UOMMaster] PRIMARY KEY CLUSTERED 
(
	[UOM_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]
GO

